node {
   def commit_id
   environment {
    registry = "hanuma/Jenkins-NodeJs-Pipe"
    registryCredential = ‘dockerhub’
  }
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'NodeJs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("hanuma33/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
