node {
   def commit_id
   environment {
    registry = "hanuma/Jenkins-NodeJs-Pipe"
    registryCredential = ‘dockerhub’
  }
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'NodeJs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('Building image') {
      steps{
        script {
          docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
}
